apiVersion: v1
description: A Helm chart for Kubernetes
name: asg-lifecycle-manager
version: 0.1.0
home: https://github.com/logicmonitor/k8s-asg-lifecycle-manager
sources:
  - https://github.com/cgws/k8s-asg-lifecycle-manager
