apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: docker-registry-logicmonitor-net
      serviceAccountName: {{ .Values.service.name }}
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NODEMAN_AWS_REGION
          value: "{{ .Values.awsRegion }}"
        - name: NODEMAN_AWS_SQS_QUEUE_URL
          value: "{{ .Values.awsSqsQueueURL }}"
        - name: NODEMAN_DEBUG
          value: "{{ .Values.debug }}"
        ports:
        - containerPort: {{ .Values.service.metrics.port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.metrics.port }}
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.metrics.port }}
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: "25Mi"
          limits:
            cpu: 50m
            memory: "50Mi"
